version: "3.8"
name: nodets-rest-api-boilerplate

services:
  # App Service
  app:
    container_name: nodets-rest-api-server
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - 2222:2222 # main app
      - 5555:5555 # prisma studio
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    # networks:
    #   - default_netwowrk

  # PostgreSQL
  postgres:
    container_name: nodets-rest-api-postgres
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    # networks:
    #   - default_netwowrk

  # Swagger UI
  swagger-ui:
    container_name: nodets-rest-api-swagger-ui
    image: swaggerapi/swagger-ui:latest
    hostname: swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./docs/api:/docs
    environment:
      - SWAGGER_JSON=/docs/openapi-docs.yml

  rabbitmq:
    container_name: nodets-rest-api-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    # networks:
    #   - default_netwowrk

volumes:
  pgdata:
# networks:
#   default_netwowrk:
#     driver: bridge
